/* GENERATED by scripts/build-themes.mjs — do not edit by hand. */

/** The default. Rendered by `:root`, so it carries no `data-theme`. */
export const DEFAULT_THEME = 'terracotta';

export interface ColorTheme {
  name: string;
  label: string;
}

export const COLOR_THEMES: ColorTheme[] = [
  { name: 'terracotta', label: 'Terracotta' },
  { name: 'indigo', label: 'Indigo' },
  { name: 'emerald', label: 'Emerald' },
  { name: 'violet', label: 'Violet' },
  { name: 'amber', label: 'Amber' },
  { name: 'slate', label: 'Slate' },
];

export const isColorTheme = (value: unknown): value is string =>
  typeof value === 'string' && COLOR_THEMES.some((t) => t.name === value);
