-- The public careers page.
--
-- `JobOpening.slug` is the public URL for a role, and it is nullable on
-- purpose — that is the whole safety story here. Every opening that predates
-- this gets NULL, which the public list reads as "not published". A column
-- defaulted to something derived from the title would have put existing DRAFT
-- and CLOSED roles on the open internet the moment it deployed. The unique
-- index tolerates NULLs, so any number of unpublished openings coexist.
--
-- `Document.uploadedById` loses NOT NULL because some uploads genuinely have
-- no user behind them: a CV arriving through the careers page is posted by
-- somebody with no account, no employee record and no session. `AuditLog`
-- made the same call for the same reason — the daily lifecycle tick has no
-- actor — and before this the only way to store one was to attribute it to
-- somebody who had not done it. Dropping NOT NULL widens the column, so every
-- existing row and every existing write stays valid.
--
-- Generated by `prisma migrate diff --from-schema <previous> --to-schema`,
-- run from apps/api. From the repo root it silently emits nothing and exits 0.

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "uploadedById" DROP NOT NULL;

-- AlterTable
ALTER TABLE "JobOpening" ADD COLUMN     "slug" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "JobOpening_organizationId_slug_key" ON "JobOpening"("organizationId", "slug");
