-- Income tax: configuration, declarations and the TDS override.
--
-- Eight tables and three enums, and nothing else: every ALTER TABLE below
-- targets a table this migration itself creates. Organization and Employee
-- gain relation arrays in the Prisma schema, which emit no DDL.
--
-- The shape carries three separations that matter.
--
-- TaxConfiguration holds slabs, limits and rates as ROWS. A Finance Act change
-- is then a configuration edit rather than a release — the same bargain the
-- payroll settings already make for PF, ESI and professional tax. It ships
-- with a status of UNCONFIRMED, and payroll refuses to compute against an
-- unconfirmed year rather than falling back to last year's slabs. That is the
-- same device FVU_SPEC_VERSION = 'UNTRANSCRIBED' uses for the 24Q layout.
--
-- EmployeeTaxDeclarationItem keeps four figures apart — declared, statutory
-- limit, eligible, approved. Tax is computed from the approved figure and
-- never from what somebody typed, and the limit is snapshotted so the row
-- still explains itself after the rules are edited.
--
-- TdsOverride keeps the calculated figure beside the overridden one. An
-- override whose original is lost is an override nobody can audit.
--
-- Nothing here computes Form 24Q. The return reads actual payslip lines, as it
-- always has (docs/16-adr-001-form-24q.md).
--
-- Generated by `prisma migrate diff --from-schema <previous> --to-schema`, not
-- hand-written.


-- CreateEnum
CREATE TYPE "TaxRegime" AS ENUM ('NEW', 'OLD');

-- CreateEnum
CREATE TYPE "TaxConfigStatus" AS ENUM ('UNCONFIRMED', 'CONFIRMED');

-- CreateEnum
CREATE TYPE "TaxDeclarationStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED');

-- CreateTable
CREATE TABLE "TaxConfiguration" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "financialYear" TEXT NOT NULL,
    "regime" "TaxRegime" NOT NULL,
    "status" "TaxConfigStatus" NOT NULL DEFAULT 'UNCONFIRMED',
    "source" TEXT,
    "standardDeduction" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "rebateIncomeLimit" DECIMAL(14,2),
    "rebateMaxAmount" DECIMAL(14,2),
    "cessRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "marginalRelief" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaxConfiguration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaxSlab" (
    "id" TEXT NOT NULL,
    "configurationId" TEXT NOT NULL,
    "fromAmount" DECIMAL(14,2) NOT NULL,
    "toAmount" DECIMAL(14,2),
    "rate" DECIMAL(5,2) NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TaxSlab_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaxDeductionRule" (
    "id" TEXT NOT NULL,
    "configurationId" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "hint" TEXT,
    "maxAmount" DECIMAL(14,2),
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TaxDeductionRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaxSurchargeBand" (
    "id" TEXT NOT NULL,
    "configurationId" TEXT NOT NULL,
    "aboveIncome" DECIMAL(14,2) NOT NULL,
    "rate" DECIMAL(5,2) NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TaxSurchargeBand_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeTaxProfile" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "financialYear" TEXT NOT NULL,
    "regime" "TaxRegime" NOT NULL DEFAULT 'NEW',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmployeeTaxProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeTaxDeclaration" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "financialYear" TEXT NOT NULL,
    "status" "TaxDeclarationStatus" NOT NULL DEFAULT 'DRAFT',
    "annualRentPaid" DECIMAL(14,2),
    "metroCity" BOOLEAN NOT NULL DEFAULT false,
    "submittedAt" TIMESTAMP(3),
    "decidedById" TEXT,
    "decidedAt" TIMESTAMP(3),
    "decisionNote" TEXT,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmployeeTaxDeclaration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeTaxDeclarationItem" (
    "id" TEXT NOT NULL,
    "declarationId" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "declaredAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "statutoryLimit" DECIMAL(14,2),
    "eligibleAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "approvedAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,

    CONSTRAINT "EmployeeTaxDeclarationItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TdsOverride" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "calculatedTds" DECIMAL(14,2) NOT NULL,
    "overrideTds" DECIMAL(14,2) NOT NULL,
    "reason" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TdsOverride_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TaxConfiguration_organizationId_financialYear_idx" ON "TaxConfiguration"("organizationId", "financialYear");

-- CreateIndex
CREATE UNIQUE INDEX "TaxConfiguration_organizationId_financialYear_regime_key" ON "TaxConfiguration"("organizationId", "financialYear", "regime");

-- CreateIndex
CREATE INDEX "TaxSlab_configurationId_order_idx" ON "TaxSlab"("configurationId", "order");

-- CreateIndex
CREATE UNIQUE INDEX "TaxDeductionRule_configurationId_section_key" ON "TaxDeductionRule"("configurationId", "section");

-- CreateIndex
CREATE INDEX "TaxSurchargeBand_configurationId_order_idx" ON "TaxSurchargeBand"("configurationId", "order");

-- CreateIndex
CREATE INDEX "EmployeeTaxProfile_organizationId_financialYear_idx" ON "EmployeeTaxProfile"("organizationId", "financialYear");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeTaxProfile_employeeId_financialYear_key" ON "EmployeeTaxProfile"("employeeId", "financialYear");

-- CreateIndex
CREATE INDEX "EmployeeTaxDeclaration_organizationId_financialYear_status_idx" ON "EmployeeTaxDeclaration"("organizationId", "financialYear", "status");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeTaxDeclaration_employeeId_financialYear_key" ON "EmployeeTaxDeclaration"("employeeId", "financialYear");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeTaxDeclarationItem_declarationId_section_key" ON "EmployeeTaxDeclarationItem"("declarationId", "section");

-- CreateIndex
CREATE INDEX "TdsOverride_organizationId_month_idx" ON "TdsOverride"("organizationId", "month");

-- CreateIndex
CREATE UNIQUE INDEX "TdsOverride_employeeId_month_key" ON "TdsOverride"("employeeId", "month");

-- AddForeignKey
ALTER TABLE "TaxConfiguration" ADD CONSTRAINT "TaxConfiguration_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaxSlab" ADD CONSTRAINT "TaxSlab_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "TaxConfiguration"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaxDeductionRule" ADD CONSTRAINT "TaxDeductionRule_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "TaxConfiguration"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaxSurchargeBand" ADD CONSTRAINT "TaxSurchargeBand_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "TaxConfiguration"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeTaxProfile" ADD CONSTRAINT "EmployeeTaxProfile_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeTaxProfile" ADD CONSTRAINT "EmployeeTaxProfile_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeTaxDeclaration" ADD CONSTRAINT "EmployeeTaxDeclaration_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeTaxDeclaration" ADD CONSTRAINT "EmployeeTaxDeclaration_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeTaxDeclarationItem" ADD CONSTRAINT "EmployeeTaxDeclarationItem_declarationId_fkey" FOREIGN KEY ("declarationId") REFERENCES "EmployeeTaxDeclaration"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TdsOverride" ADD CONSTRAINT "TdsOverride_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TdsOverride" ADD CONSTRAINT "TdsOverride_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

